Bugfix/resources title adjustments 97
pk-hotovo/swagger-ui-kong-theme pull request #38
Opened 2022-07-19 15:31 UTC by pk-hotovo

issue 97

2022-07-19 15:46 UTC, tomaszwylezek commented on src/styles/main.css
> +  border-bottom: 1px solid var(--green-500);
It shouldn't change color to green

2022-07-19 15:46 UTC, tomaszwylezek commented on src/styles/main.css
> +  border-bottom: 1px solid var(--black-200);
border-bottom should be `--section_colors-stroke` 
Same for the whole border of Shemas/Models

2022-07-21 07:26 UTC, tomaszwylezek requested changes
**Expected result**
![Screenshot 2022-07-21 at 09 23 35](https://user-images.githubusercontent.com/16152347/180154681-fbc97664-8e14-4334-b9f7-7aa890d82f3e.png)

**Previous result**
![Screenshot 2022-07-21 at 09 24 44](https://user-images.githubusercontent.com/16152347/180154738-75479342-8d0d-408f-a904-5ca3f6db7baa.png)

**Current branch result**
![Screenshot 2022-07-21 at 09 24 10](https://user-images.githubusercontent.com/16152347/180154786-76fef8f1-815e-4012-8071-985bceba2e04.png)

The changes wouldn't get rid of margin on both side of the container, that change is unexpected.
The titles like `auth` `HTTP methods and `Status code` are still not aligned with boxes

2022-07-21 10:25 UTC, pk-hotovo commented
The titles like auth HTTP methods and Status code` are still not aligned with boxes - can you please explain what it means in this context?

2022-07-21 11:28 UTC, pk-hotovo commented
updated

2022-07-21 12:27 UTC, tomaszwylezek commented on src/styles/main.css
> +  padding: var(--spacing-xl) 0;
it shouldn't change

2022-07-21 12:46 UTC, tomaszwylezek requested changes
It is not aligned with the boxes
![Screenshot 2022-07-21 at 14 45 30](https://user-images.githubusercontent.com/16152347/180216601-3f1fb3de-ac39-4c0e-bef2-796da4f87934.png)
We need to remove that padding-left from that button

2022-07-21 15:21 UTC, tomaszwylezek approved these changes
lgtm

2022-07-22 07:46 UTC, merged